hipogram/posts/urls.py
from django.urls import path

from .views import post_list_view

app_name = "posts"

urlpatterns = [
    path("", post_list_view, name="list"),
]

hipogram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hipogram.posts.urls", namespace="posts")),
    path("", include("hipogram.users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hipogram/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import signup_view

app_name = "users"

urlpatterns = [
    path("signup/", signup_view, name="signup"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

hipogram/posts/models.py
from django.db import models


class Post(models.Model):
    image = models.ImageField()
    text = models.TextField()
    created_by = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    creation_datetime = models.DateTimeField(auto_now_add=True)

hipogram/posts/views.py
from django.shortcuts import render

from .models import Post


def post_list_view(request):
    posts = Post.objects.all().order_by("-creation_datetime")
    return render(request, "post_list.html", {'posts': posts})

hipogram/users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "signup.html", {"form": form})

hipogram/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>{% block title %}Hipogram{% endblock %}</title>
    <!---------- CSS ----------->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
    {% block css %}{% endblock %}
    <!-------------------------->
  </head>
  <body>
    {% block body %}
      {% include "navbar.html" %}
      <div class="container-fluid mt-5">
        {% block content %}{% endblock %}
      </div>
    {% endblock body %}
    <!------- JavaScript ------->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block js %}{% endblock %}
    <!-------------------------->
  </body>
</html>

hipogram/core/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand ml-5" href="{% url "posts:list" %}">Hipogram</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse mr-5" id="navbarNav">
    {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="{% url "users:logout" %}">Log out</a>
          </div>
        </li>
      </ul>
    {% else %}
      <form class="form-inline ml-auto">
        <a href="{% url "users:login" %}" class="btn btn-outline-light">Log in</a>
        <a href="{% url "users:signup" %}" class="btn btn-light ml-2">Sign up</a>
      </form>
    {% endif %}
  </div>
</nav>

hipogram/posts/templates/post_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    {% for post in posts %}
      <div class="card mb-3">
        <div class="card-body">
          <h2 class="card-title">{{ post.created_by.username }}</h2>
          <img class="img-fluid mb-3" style="max-height:400px" src="{{ post.image.url }}"/>
          <p class="card-text">{{ post.text }}</p>
        </div>
        <small class="card-footer text-muted text-right p-2">{{ post.creation_datetime|date:"H:i - d.m.Y" }}</small>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

hipogram/users/templates/form_card.html
{% load crispy_forms_tags %}

<div class="row justify-content-center">
  <div class="col-3">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title mb-5">{{ title }}</h3>
        <form method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary btn-block">{{ button_text }}</button>
        </form>
      </div>
    </div>
  </div>
</div>

hipogram/users/templates/login.html
{% extends "base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
  {% include "form_card.html" with title="Log in" button_text="Log in" %}
  <div class="text-center text-muted mt-1">
    Do not have an account? <a href="{% url "users:signup" %}">Sign up</a>
  </div>
{% endblock content %}

hipogram/users/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
  {% include "form_card.html" with title="Sign up" button_text="Sign up" %}
  <div class="text-center text-muted mt-1">
    Already have an account? <a href="{% url "users:login" %}">Log in</a>
  </div>
{% endblock content %}